services:

  postgresql:
    image: postgres:16.5-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    command: postgres -c max_connections=20
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
