app:
  bank:
    secret-value: ${API_SECRET}
    api-key: ${BUNQ_APIKEY}
    bank-account-id: ${BUNQ_BANK_ACCOUNT_ID}
    transaction-limit: 20 # up this when pagination is built (max is 200 from bunq)
    cache:
      balance:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
        maximum-size: 1
      transactions:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
        maximum-size: 1

spring:
  security:
    user:
      password: ${ADMIN_PASSWORD}
      name: ${ADMIN_USERNAME}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate.ddl-auto: validate
    generate-ddl: true
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  cloud.gcp.sql:
    instance-connection-name: ${INSTANCE_CONNECTION_NAME}
    database-name: ${DATABASE_NAME}

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

    serialization:
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false

springfox:
  documentation:
    swagger:
      v2:
        path: /internal/api-docs


