app:
  bank:
    secret-value: ${API_SECRET:geheim}
    api-key: ${BUNQ_APIKEY:averylongdifficultkey}

spring:
  security:
    user:
      password: ${ADMIN_PASSWORD:geheim}
      name: admin
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      base-path: /_ah

springfox:
  documentation:
    swagger:
      v2:
        path: /internal/api-docs