app:
  bank:
    secret-value: geheim
    api-key: ${BUNQ_APIKEY:averylongdifficultkey}

spring:
  security:
    user:
      password: ${ADMIN_PASSWORD:geheim}
      name: admin


server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      base-path: /_ah