app:
  bank:
    saveSessionToFile: true

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
