app:
  bank:
    secret-value: ${API_SECRET}
    api-key: ${BUNQ_APIKEY}

spring:
  security:
    user:
      password: ${ADMIN_PASSWORD}
      name: ${ADMIN_USERNAME}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate.ddl-auto: create-drop
    generate-ddl: true
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  cloud.gcp.sql:
    instance-connection-name: ${INSTANCE_CONNECTION_NAME}
    database-name: ${DATABASE_NAME}

  jackson.serialization:
    WRITE_DATES_AS_TIMESTAMPS: true
    WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false

springfox:
  documentation:
    swagger:
      v2:
        path: /internal/api-docs


