app:
  bank:
    secret-value: ${API_SECRET}
    api-key: ${BUNQ_APIKEY}
    bank-account-id: ${BUNQ_BANK_ACCOUNT_ID}
    transaction-limit: 20 # up this when pagination is built (max is 200 from bunq)
    saveSessionToFile: true #tmp
    cache:
      balance:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
        maximum-size: 1
      # FIXME: Current impl uses balance config for both
      transactions:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
        maximum-size: 1


micronaut:
  security:
    enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**


server:
  forward-headers-strategy: NATIVE
spring:
  security:
    user:
      password: ${ADMIN_PASSWORD}
      name: ${ADMIN_USERNAME}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate.ddl-auto: validate
    generate-ddl: true
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 2
#    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
#    url: jdbc:postgresql://sql_proxy:5432/${DATABASE_NAME}
  cloud.gcp.sql:
    instance-connection-name: ${INSTANCE_CONNECTION_NAME}
    database-name: ${DATABASE_NAME}

  jackson:
    serialization:
      write_dates_as_timestamps: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false

springfox:
  documentation:
    swagger:
      v2:
        path: /internal/api-docs


