app:
  title: "Team balance"
  description: "Fancy pants teampot for sport teams w/ regular events and drinks"
  version: "@project.version@-@git.commit.id.describe@"
  bank:
    bunq:
      api-key: ${sm://BUNQ_APIKEY}
      environment: PRODUCTION
    transaction-limit: 200 # up this when pagination is built (max is 200 from bunq)
    cache:
      balance:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
      transactions:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
  multi-tenancy:
    tenants:
      - domain: heren4.tovoheren5.nl # temporary setup
        secret: ${sm://API_SECRET_TOVO_HEREN_4}
        bunq-me-base-url: ${sm://TOVO_HEREN_4_BUNQ_ME}
        tenant: tovo_heren_4
        title: "Tovo Heren 4"

      - domain: tovoheren5.nl
        secret: ${sm://API_SECRET_TOVO_HEREN_5}
        bunq-me-base-url: ${sm://TOVO_HEREN_5_BUNQ_ME}
        tenant: tovo_heren_5
        title: "Tovo Heren 5"

server:
  forward-headers-strategy: NATIVE
  shutdown: graceful
spring:
  config:
    import: "sm://"
  cloud:
    gcp:
      project-id: ${sm://GCP_PROJECT_ID}
  devtools:
    add-properties: false
  datasource:
    username: override-me
    password: override-me
    url: override-me
    hikari:
      maximum-pool-size: 1
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write_dates_as_timestamps: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"
    enabled: true
  security:
    user:
      password: ${sm://ADMIN_PASSWORD}
      name: ${sm://ADMIN_USERNAME}
      roles:
        - admin
        - user
springdoc:
  model-and-view-allowed: true
  swagger-ui:
    path: /internal/openapi/
    doc-expansion: none
  api-docs:
    groups.enabled: true
    path: /internal/openapi/v3/api-docs
  paths-to-match: /api/**
  writer-with-order-by-keys: true

management:
  endpoint:
    info:
      enabled: true
  info:
    build:
      enabled: true
    git:
      mode: simple
  endpoints:
    web:
      base-path: /internal/actuator
      exposure:
        include: health,info
