app:
  bank:
    bunq:
      api-key: ""
      environment: SANDBOX
      saveSessionToFile: true
    transaction-limit: 200 # up this when pagination is built (max is 200 from bunq)
    cache:
      balance:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
      transactions:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
  competition:
    cache-config:
      enabled: true
      expire-after-write: 1m
      refresh-after-write: 30s
  multi-tenancy:
    tenants:
      - domain: localhost:8080
        secret: teambalance
        bunq-me-base-url: https://bunq.com/local
        tenant: tovo_heren_4
        title: "localhost:8080"
      - domain: localhost:3000
        secret: teambalance
        bunq-me-base-url: https://bunq.com/5
        tenant: tovo_heren_4
        title: "localhost:3000"
      # for docker-compose
      - domain: backend:8080
        secret: teambalance
        bunq-me-base-url: https://bunq.com/5
        tenant: tovo_heren_4
        title: "frontend:3000"
      - domain: 5.teambalance.local:8080
        secret: teambalance
        bunq-me-base-url: https://bunq.com/5
        tenant: tovo_heren_5
        title: "Tovo Heren 5 (local 8080)"
      - domain: 5.teambalance.local:3000
        secret: teambalance
        bunq-me-base-url: https://bunq.com/5
        tenant: tovo_heren_5
        title: "Tovo Heren 5 (local 3000)"
      - domain: 4.teambalance.local:8080
        secret: teambalance
        bunq-me-base-url: https://bunq.com/4
        tenant: tovo_heren_4
        title: "Tovo Heren 4 (local 8080)"
      - domain: 4.teambalance.local:3000
        secret: teambalance
        bunq-me-base-url: https://bunq.com/4
        tenant: tovo_heren_4
        title: "Tovo Heren 4 (local 3000)"

spring:
  datasource:
    username: teambalance
    password: teambalance
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54321}/teambalance
  devtools:
    add-properties: true
  security:
    user:
      password: admin
      name: admin
      roles:
        - admin
        - user
  liquibase:
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


logging:
  level:
    nl.jvandis.teambalance: debug
#    org.jooq: debug
