server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      base-path: /_ah

spring:
  datasource:
    username: ${sm://DB_USERNAME}
    password: ${sm://DB_PASSWORD}
    url: ${sm://DB_URL}
#spring:
#  datasource:
#    url: ${CLOUD_INSTANCE_CONNECTION_NAME}
