events {
  worker_connections 1024;
}
http {
  server {
    index index.html;
    root /var/www;

    location / {
      limit_except GET {
        auth_basic "Nginx Maven Build Cache";
        auth_basic_user_file /etc/nginx/conf.d/nginx.htpasswd;
      }
      autoindex on;
      dav_methods PUT DELETE MKCOL COPY MOVE;
      create_full_put_path on;
      dav_access group:rw  all:r;
    }
  }
}
