app:
  bank:
    bunq:
      saveSessionToFile: true

spring:
  jpa:
    show-sql: true
  datasource:
    username: ${sm://DB_USERNAME_DEV}
    password: ${sm://DB_PASSWORD_DEV}
    url: ${sm://DB_URL_DEV}
  devtools:
    add-properties: true
