management.endpoints.web:
  base-path: /internal/actuator
app:
  title: "Team balance"
  description: "Fancy pants teampot for Tovo heren 5"
  version: "@project.version@-@git.commit.id.describe@"
  datetime-limit: ${app.bank.datetime-limit}
  secret:
    secret-value: ${sm://API_SECRET}
  bank:
    bunq:
      api-key: ${sm://BUNQ_APIKEY}
      bank-account-id: ${sm://BUNQ_BANK_ACCOUNT_ID}
      environment: PRODUCTION
    transaction-limit: 200 # up this when pagination is built (max is 200 from bunq)
    datetime-limit: 2022-08-01T00:00:00+02:00
    cache:
      balance:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
        maximum-size: 1
      transactions:
        enabled: true
        expire-after-write: 60s
        refresh-after-write: 30s
        maximum-size: 1

server:
  forward-headers-strategy: NATIVE
spring:
  devtools:
    add-properties: false
  cloud:
    gcp:
      project-id: ${sm://GCP_PROJECT_ID}
  security:
    user:
      password: ${sm://ADMIN_PASSWORD}
      name: ${sm://ADMIN_USERNAME}
      roles:
        - admin
        - user
  datasource:
    username: override-me
    password: override-me
    url: override-me
    hikari:
      maximum-pool-size: 1
  jackson:
    serialization:
      write_dates_as_timestamps: false
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"
    enabled: true

springdoc:
  model-and-view-allowed: true
  swagger-ui:
    path: /internal/openapi/
    doc-expansion: none
  api-docs:
    groups.enabled: true
    path: /internal/openapi/v3/api-docs
  paths-to-match: /api/**
  writer-with-order-by-keys: true
management:
  endpoint:
    info:
      enabled: true
  info:
    build:
      enabled: true
    git:
      mode: simple
  endpoints:
    web:
      exposure:
        include: health,info
