# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on: [pull_request]

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      pull-requests: write
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Apply maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Apply npm-cache
        uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build app
        run: make ci

      - name: Postgres
        run: |
          docker compose up -d
          sleep 15

      - name: E2E tests
        run: make e2e
        env:
          HOST: http://localhost:3000
          PASSWORD: teambalance

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30

      - name: Add Playwright Github comment
        uses: daun/playwright-report-summary@v3
        if: ${{ !cancelled() }}
        with:
          report-file: e2e/results.json

      - name: Teardown postgres
        if: always()
        run: docker compose down
