# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on: [pull_request]

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      pull-requests: write
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3

      - name: Apply maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Apply npm-cache
        uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build app
        run: make ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#      - name: Expose GitHub Runtime
#        uses: crazy-max/ghaction-github-runtime@v3
#
      - name: API tests
        run: make test

      - name: Build and push Docker image with caching
        run: |
          cd frontend && docker buildx build \
            --cache-from=type=registry,ref=eu.gcr.io/tovoheren5/cache-teambalance \
            --cache-to=type=registry,ref=eu.gcr.io/tovoheren5/cache-teambalance,mode=max \
            -t eu.gcr.io/tovoheren5/ci-image-frontend-teambalance . \
            --push

      - name: Build / cache frontend image
        uses: docker/build-push-action@v5
        with:
          # Don't push in this step
          load: true
#          push: true
          # Build the frontend image
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: teambalance/frontend:latest
          # Setup caching
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Do the same for e2e image
      - name: Build / cache e2e image
        uses: docker/build-push-action@v5
        with:
          load: true

          context: ./e2e
          tags: teambalance/e2e:latest
          file: ./e2e/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: E2E tests
        run: make e2e  || (docker compose logs frontend && exit 1)

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30

      - name: Add Playwright Github comment
        uses: daun/playwright-report-summary@v3
        if: ${{ !cancelled() }}
        with:
          report-file: e2e/results.json

      - name: Teardown docker containers
        if: always()
        run: docker compose down
